#!/bin/sh

set -e

#DEBHELPER#

# Automatically added by dh_installinit
if [ -x "/etc/init.d/psi-client" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d psi-client stop || exit $?
	else
		/etc/init.d/psi-client stop || exit $?
	fi
fi
# End automatically added section
